version: '3'

services:
  ##############################
  ### SETUP SERVER CONTAINER ###
  ##############################
  server:
    build:
      context: ./back-end
    container_name: server
    expose:
      - 4000
    ports:
      - 4000:4000
    environment:
      - PORT=4000
    volumes:
      - ./back-end/src:/app/server/src
      - ./back-end/src/static/image-tmp:/app/server/static/image-tmp
      - ./back-end/src/static/styles:/app/server/static/styles
      - ./back-end/src/templates:/app/server/static/templates
      - /etc/localtime:/etc/localtime:ro
    restart: always
    links:
      - cnn

  #############################
  ###  SETUP CNN CONTAINER  ###
  #############################
  cnn:
    build:
      context: ./CNN
    container_name: cnn
    expose:
      - 5000
    ports:
      - 5000:5000

    volumes:
      - ./CNN/src:/app/cnn/src
      - ./back-end/src/image-tmp:/app/cnn/src/image-tmp
      - /etc/localtime:/etc/localtime:ro
    restart: always
