version: '3'

services:
  ##############################
  ### SETUP SERVER CONTAINER ###
  ##############################
  server:
    build:
      context: ./back-end
    container_name: server
    expose:
      - 8000
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - ./back-end/src:/app/server/src
      - ./back-end/src/static/image-tmp:/app/server/static/image-tmp
      - ./back-end/src/static/styles:/app/server/static/styles
      - ./back-end/src/templates:/app/server/static/templates
      - /etc/localtime:/etc/localtime:ro
    restart: always
    links:
      - cnn

  #############################
  ###  SETUP CNN CONTAINER  ###
  #############################
  cnn:
    build:
      context: ./CNN
    container_name: cnn
    expose:
      - 7000
    ports:
      - "7000:7000"
    environment:
      - PORT=7000
    volumes:
      - ./CNN/src:/app/cnn/src
      - ./back-end/src/image-tmp:/app/cnn/src/image-tmp
      - /etc/localtime:/etc/localtime:ro
    restart: always

  #############################
  ###  SETUP CNN CONTAINER  ###
  #############################
  bot:
    build:
      context: ./tg-bot
    container_name: bot
    expose:
      - 6000
    ports:
      - "6000:6000"
    environment:
      - G_TOKEN
      - TG_TOKEN
    volumes:
      - ./CNN/src:/app/cnn/src
      - ./back-end/src/image-tmp:/app/cnn/src/image-tmp
      - /etc/localtime:/etc/localtime:ro
    restart: always
